### PR TITLE
Remove () from foreachBetween signature.

### PR DESCRIPTION
**Pull request by cseed**

### CODE REVIEW

**Comment by tpoterba** [comment]
Looks good, but need to rebase.

**Comment by cseed** [comment]
jenkins

**Comment by cseed** [comment]
jenkins

**Comment by cseed** [comment]
jenkins

**Comment by cseed** [comment]
jenkins

**Comment by tpoterba** [comment]
jenkins is taking his sweet time with this one

**Comment by cseed** [comment]
It ran out of space and I messed some stuff up trying to get it going again.  I think it's back on track now although it has a backlog to get through.

**Comment by cseed** [comment]
OK, it's ready!

**Pull request merged**
