### PR TITLE
hard call sets and t2d service

### PR DESCRIPTION
**Pull request by jbloom22**
- removed LinearRegressionFromHcsCommand and test
- removed extraneous JSON files

### CODE REVIEW

**Comment by jbloom22** [comment]
@cseed let's continue with the t2d PR here.

**Comment by jbloom22** [comment]
I deleted the LinearRegressionFromHcsCommand and associated tests as it'd fallen out of sync with how hcs evolved for T2D, it's independent of the rest of the PR and I can add this functionality back later (at which point I imagine there will be other changes both to hcs and to the stats interfaces more generally).

**Comment by cseed** [comment]
This is failing because the server in the test tries to use the same port (8080) as Jenkins.  I'm going to move Jenkins.

**Comment by cseed** [comment]
jenkins

**Comment by cseed** [comment]
jenkins

**Comment by jbloom22** [comment]
jenkins

**Comment by jbloom22** [comment]
closing...will re-issue pr from forked repository

**Pull request closed without merging**
