### PR TITLE
Jg grouptest

### PR DESCRIPTION
**Pull request by jigold**

### CODE REVIEW

**Comment by jigold** [comment]
jenkins

**Comment by jigold** [comment]
jenkins

**Comment by jigold** [comment]
jenkins

**Comment by jigold** [comment]
jenkins

**Comment by jigold** [comment]
I have the FET in the expr language done. Also in this branch is the linear regression code refactoring. I removed the docs for the group tests, but left the code for creating groups and the FET and linear regression group tests in this branch.

**Comment by cseed** [comment]
@jigold Based on our last conversion to call out to R for SKAT-O, do you want to close this pull request and make a separate one for FET?

**Pull request closed without merging**
