### PR TITLE
Added annotatevariants positions.

### PR DESCRIPTION
**Pull request by tpoterba**
Added vsm.annotatePositions function.

Added GenomicIndex case class (contig, start), and added function to Variant to extract it

### CODE REVIEW

**Comment by tpoterba** [comment]
jenkins

**Comment by tpoterba** [comment]
@cseed: I feel somewhat guilty about duplicating a large amount of `AnnotateVariantsTable` code here, almost all of it.  However, it isn't totally easy to refactor.

I'm also happy to rename "GenomicIndex" to something better.

**Comment by cseed** [comment]
You used `GenomicIndex`, but I added `Locus` in the interval changes.  Can you rebase?

**Comment by tpoterba** [comment]
This guy will be totally retooled with the table changes, so I'll wait for that to go in too.  The GenomicIndex here actually predated the interval rewrite

**Comment by cseed** [comment]
Closed for retooling.

**Pull request closed without merging**
