### PR TITLE
Rewrote interval lists to support future work in interval aggregation

### PR DESCRIPTION
**Pull request by tpoterba**

### CODE REVIEW

**Comment by tpoterba** [comment]
jenkins

**Comment by tpoterba** [comment]
Again, happy to take criticism on names / structure

**Comment by tpoterba** [comment]
I think this API is a lot cleaner though

**Comment by tpoterba** [comment]
jenkins

**Comment by tpoterba** [comment]
jenkins

**Comment by tpoterba** [comment]
I did a benchmarking experiment.
My inputs:
 > **VDS**: vds created from `seq 1 100 300000000` mapped to "1  $i   A   T   NA", and imported with `hail importannotations`.  This is a 3M variant sites vds.
> **interval file**: exome capture regions provided by Monkol.  Seems like pretty random non-overlapping interval over chr1.  39K variants fall in these intervals, slightly over 1%.

My cmd line:
```hail read -i <vds> filtervariants intervals --keep -i <interval list>  count```, with the read/filter/count repeated 10 times.  I ran this on the current master and this branch on one core on my laptop.  I then calculated the time per iteration.

**Benchmark results**
current master: 4.876s, with a std dev of  0.18
this branch: 4.716s, with a std dev of  0.18
mean ratio: 0.967

**Conclusion**: this branch is faster than master for interval queries by 3-4%

**Comment by tpoterba** [comment]
Note that it does take *slightly* longer to prepare an interval list on the master, about 250ms for the 220k intervals I got from Monkol.

**Comment by cseed** [comment]
jenkins

**Pull request merged**
