### PR TITLE
add styling for code inside of an anchor

### PR DESCRIPTION
**Pull request by danking**

### CODE REVIEW

**Comment by danking** [comment]
@cseed, this carries anchor style down to `code` elements contained within them. I don't know if this is ideal, but it's at least consistent with anchors and informs the user that they can click the command names.

**Comment by cseed** [comment]
Hmm, so we're writing

```
[`importbgen`](#importbgen)
```

which is code inside anchor.  Should we just put the anchor inside the code?

**Comment by cseed** [comment]
Oh, that doesn't work, because markdown rendered inside code blocks.  Hmm.

**Comment by cseed** [comment]
I don't see a better way to do this.  I folded this change in with some other link styling changes I made (increased contrast, underline on hover) and put them in the same styling block as anchors, so we don't have to change them in two places: https://github.com/broadinstitute/hail/pull/651.

**Pull request closed without merging**
